-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.verifications
(
    fid bigint NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone,
    CONSTRAINT verifications_pkey PRIMARY KEY (fid, address),
    CONSTRAINT verifications_fid_fkey FOREIGN KEY (fid)
        REFERENCES public.profiles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.verifications
    OWNER to postgres;

ALTER TABLE IF EXISTS public.verifications
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.verifications TO anon;

GRANT ALL ON TABLE public.verifications TO authenticated;

GRANT ALL ON TABLE public.verifications TO postgres;

GRANT ALL ON TABLE public.verifications TO service_role;

ALTER TABLE IF EXISTS public.profiles DROP COLUMN IF EXISTS connected_address;

ALTER TABLE IF EXISTS public.profiles DROP COLUMN IF EXISTS telegram;

ALTER TABLE IF EXISTS public.casts
    ALTER COLUMN author_fid SET STORAGE PLAIN;
ALTER TABLE IF EXISTS public.casts
    ADD CONSTRAINT casts_author_fid_fkey FOREIGN KEY (author_fid)
    REFERENCES public.profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
