-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.profiles
(
    id bigint NOT NULL,
    address text COLLATE pg_catalog."default",
    username text COLLATE pg_catalog."default",
    display_name text COLLATE pg_catalog."default",
    avatar_url text COLLATE pg_catalog."default",
    avatar_verified boolean,
    followers bigint,
    following bigint,
    bio text COLLATE pg_catalog."default",
    telegram text COLLATE pg_catalog."default",
    referrer text COLLATE pg_catalog."default",
    connected_address text COLLATE pg_catalog."default",
    registered_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT profiles_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.profiles
    OWNER to postgres;

ALTER TABLE IF EXISTS public.profiles
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;

CREATE TABLE IF NOT EXISTS public.casts
(
    hash text COLLATE pg_catalog."default" NOT NULL,
    thread_hash text COLLATE pg_catalog."default" NOT NULL,
    parent_hash text COLLATE pg_catalog."default",
    author_fid integer NOT NULL,
    author_username text COLLATE pg_catalog."default",
    author_display_name text COLLATE pg_catalog."default",
    author_pfp_url text COLLATE pg_catalog."default",
    author_pfp_verified boolean,
    text text COLLATE pg_catalog."default" NOT NULL,
    published_at timestamp with time zone NOT NULL,
    mentions jsonb,
    replies_count integer,
    reactions_count integer,
    recasts_count integer,
    watches_count integer,
    deleted boolean DEFAULT false,
    CONSTRAINT casts_pkey PRIMARY KEY (hash)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.casts
    OWNER to postgres;

ALTER TABLE IF EXISTS public.casts
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.casts TO anon;

GRANT ALL ON TABLE public.casts TO authenticated;

GRANT ALL ON TABLE public.casts TO postgres;

GRANT ALL ON TABLE public.casts TO service_role;

CREATE OR REPLACE FUNCTION public.casts_regex(
	regex text)
    RETURNS SETOF casts 
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
  SELECT * FROM casts WHERE text ~ regex;
$BODY$;

ALTER FUNCTION public.casts_regex(text)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.casts_regex(text) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.casts_regex(text) TO anon;

GRANT EXECUTE ON FUNCTION public.casts_regex(text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.casts_regex(text) TO postgres;

GRANT EXECUTE ON FUNCTION public.casts_regex(text) TO service_role;
