-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.casts
    ADD COLUMN parent_author_fid bigint;

ALTER TABLE IF EXISTS public.casts
    ADD COLUMN parent_author_username text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.casts
    ADD CONSTRAINT casts_parent_author_fid_fkey FOREIGN KEY (parent_author_fid)
    REFERENCES public.profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
