create table "public"."signer" (
    "fid" bigint generated by default as identity not null,
    "signer" text not null,
    "name" text not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."signer" enable row level security;

CREATE UNIQUE INDEX signer_pkey ON public.signer USING btree (fid, signer);

alter table "public"."signer" add constraint "signer_pkey" PRIMARY KEY using index "signer_pkey";

alter table "public"."signer" add constraint "signer_fid_fkey" FOREIGN KEY (fid) REFERENCES profile(id) not valid;

alter table "public"."signer" validate constraint "signer_fid_fkey";


