create table "public"."event" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."event" enable row level security;

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

alter table "public"."event" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";


